### ISSUE TITLE
Buttons and LED behaviour

### ISSUE THREAD

**Issue by pauldeng** [u-blox/ubxlib_cellular_applications_xplr_iot#16]
Hi repo owner,

Appreciate your hard work.

I played a bit, I think the behaviour of buttons and leds could be improved.

Button 1:
- Current: flush log and shutdown
- Expect: flash led for battery level, e.g. green >70%, yellow > 50%, red < 50%. (Log should be flashed automatically)

Button 2:
- Current: scan network. Tried it, no idea what it does.
- Expect: maybe do nothing or scan wifi SSID and record/send it out

LED:
- Current: a bit confusing to me
- Expect: When just powered on orange, green when connected, then off. Flash LED when sending message out, the colour is based on RSSI for example. (no need to show while for location data sending)

The system in general should just need to power on and work. Button 1 and Button 2 seems a bit off.

Cheers,
Paul

**Comment by philwareublox** [comment]
Button #1 is for the graceful shutdown of the application
Button #2 is to perform a Cellular Scanning of networks, which can take a long time (minutes) the LED will/should change colour to show the cell scanning is being performed. See +COPS=?
LED colour shows the various stages of booting. Currently it will show green when everything is connected, and blip blue for the signal quality MQTT message and blip white for the Location. There are two colours here because it is good to know the GNSS has finally got a lock and it is sending out location messages now.
